---
- debug: var=service_name
- name: stop the service
  ansible.builtin.service:
    name: httpd
    state: stopped
  register: x
  when: service_name == ""
  ignore_errors: true

- name: stop the service
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: stopped
  register: xy
  when: service_name != ""
  ignore_errors: true
  
- debug: var=xy
  when: service_name != ""

- debug: var=x
  when: service_name == ""
